# Generated by Django 4.2.17 on 2025-06-11 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockin',
            name='supplier',
        ),
    ]
